version: "3.9"

networks: 
  dockernet: 

services:
  db:
    image: mysql:8
    deploy:
      replicas: 1
    environment: 
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks: 
      - dockernet

  adminer:
    image: adminer:4
    deploy:
      replicas: 1
    ports:
      - 8080:8080
    networks: 
      - dockernet
    
  backend:
    image: spm-backend
    deploy:
      replicas: 1
    environment: 
      - PouletMayo_Db__Host=db
      - PouletMayo_Db__User=root
      - PouletMayo_Db__Password=password
      - PouletMayo_Db__Database=pouletmayo
    ports:
      - 8000:8000
    networks: 
      - dockernet
      
  frontend:
    image: spm-front
    ports:
      - 9000:9000
    networks: 
      - dockernet
  nginx:
    image: nginx
    deploy:
      replicas: 1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - dockernet